---
title: "Regression"
author: "David Gerard"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Synopsis

This website contains the teaching materials for STAT 415/615 Regression, taught at American 
University by [David Gerard](https://dcgerard.github.io/).

# Administrative

- [Syllabus](./syllabus.html)

# Lectures

- 00 Motivation
  - [Lecture 00-1: Linear Regression Overview](./00_motivation.html).
- 01 Crash Course in R
  - [Lecture 01-1: R introduction](./01_r_intro.html).
  - [Lecture 01-2:  R markdown introduction](01_r_markdown.html).
  - [Lecture 01-3: R graphics with `qplot()`](./01_qplot.html).
  - [Lab 01-1: R Lab](./01_r_lab.html).
- 02 Review
  - [Lecture 02-1: Mathematical prerequisites](./02_math_prereq.html).
  - [Lecture 02-2: Probability and simulation](./02_prob_sim.html).
- 03 Simple linear regression
  - [Lecture 03-1: The Model](./03_ols.html). 
      - Chapter 1 of KNNL.
  - [Lecture 03-2: Inference](./03_inference.html). 
      - Chapter 2 of KNNL.
  - [Lecture 03-3: Diagnostics and Remedial Measures](./03_diagnostics.html). 
      - Chapter 3 of KNNL.
  - [Lecture 03-4: SLR Case Study](./03_slr_case.html).
  - [Lecture 03-5: Other Topics in SLR](./03_other_topics.html).
      - Chapter 4 of KNNL.
  - [Lab 03-1: Inference Lab](./03_inference_lab.html).
  - [Lab 03-2: Diagnostics Lab](./03_diagnostics_lab.html).
- 04 Linear algebra
  - [Lecture 04-1: Linear Algebra](./04_linear_algebra.html). 
      - Chapter 5 of KNNL.
  - [Lab 04-1: Linear Algebra Lab](./04_linear_algebra_lab.html). 
- 05 Multiple linear regression
  - [Lecture 05-1: Multiple Linear Regression](./05_mlr_i.html).
      - Model definition, interpretation, estimation, inference, assumptions.
      - Chapter 6 of KNNL.
  - [Lecture 05-2: MLR and ANOVA](./05_mlr_anova.html)
      - ANOVA perspective of hypothesis testing in the muliple linear regression model.
      - Sections 6.5, 6.9, 7.1, 7.2, and 7.3 of KNNL
  - [Lecture 05-3: MLR: Practical Considerations](./05_mlr_ii.html).
      - Standardizing predictors, multicollinearity.
      - Chapter 7 of KNNL.
      - Chapter 12 of ROS.
  - [Lecture 05-4: MLR: Quadratic Terms, Interaction Effects, and Categorical Variables](./05_mlr_iii.html).
      - Chapter 8 of KNNL.
  - [Lecture 05-5: MLR: Model Selection](./05_mlr_selection.html).
      - Chapter 12 of Statistical Sleuth.
      - Chapter 9 of KNNL.
  - [Lecture 05-6: MLR: More Complicated Model Diagnostics](05_mlr_diagnostics.html).
      - Chapter 10 of KNNL.
<!-- - 06 Design -->
<!--   - [Lecture 06-1: Design of Regression Experiments](./06_design.html). -->
<!-- - 07 Logistic Regression -->
<!--   - [Lecture 07-1: Logistic Regression](./07_logistic.html). -->
- Review Sheets
  - [Equations](./rr_equations.html).

# Final Project

- [Final Project Description](./pp_description.html).
